server:
  port: 8082

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/member
    username: root
    password: 1234

mybatis:
  mapper-locations: repository/*.xml
  type-aliases-package: msa.member.v1.member.dao

logging:
  level:
    root: INFO
    msa.member.v1.member: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
